In [1]:
import chess_game as cg
from time import time
import numpy as np

In [2]:
t = time()
a = cg.game_board()
print(time()-t)

0.0004818439483642578


In [3]:
g = cg.saved_game()

In [8]:
t = time()
asdf = g.get_next_NN_inputs(dothreats=False)
g.make_move(3)
print(time()-t)

0.030743837356567383


In [13]:
g.make_move(3)

In [14]:
g.log.shape

(4, 3)

In [12]:
t = time()
a.move('e4')
print(time()-t)

0.010129928588867188


In [16]:
t = time()
a.find_all_next_board_positions()
print(time() - t)

0.045449018478393555


In [4]:
t = time()
a.get_all_color_pieces('W')
print(time() - t)

0.00014519691467285156


In [ ]:
t = time()
a.find_legal_moves_check_check((4,1), 'W')
print(time() - t)

In [ ]:
t = time()
a.find_legal_moves((3,0))
print(time() - t)

In [ ]:
print(a.get_all_color_pieces('W'))

In [ ]:
t = time()
a.find_queenmoves((4,4), 'B')
print(time() - t)

In [ ]:
t = time()
a.find_all_next_board_positions()
w, b = a.count_threats()
print(time()-t)

In [ ]:
a.board

In [ ]:
import numpy as np
np.flip(a.board, 1)

In [3]:
t = time()
next_boards = a.find_all_next_board_positions()
next_inputs = [ele.get_NN_inputs('B') for ele in next_boards]
print(time()-t)

0.23514199256896973


In [16]:
print(a)

| r | n | b | q | k | b | n | r
| p | p | p | p | p | p | p | p
|   |   |   |   |   |   |   |  
|   |   |   |   |   |   |   |  
|   |   |   |   | P |   |   |  
|   |   |   |   |   |   |   |  
| P | P | P | P |   | P | P | P
| R | N | B | Q | K | B | N | R


In [17]:
t = time()
a.board[1,1].lower() == 'p'
print(time() - t)

7.796287536621094e-05


In [32]:
t = time()
a.board[1,1] in ["P", "p"]
print(time() - t)

6.794929504394531e-05


In [5]:
next_boards[0].wthreats

array([[ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  3.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  4.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  3.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.]])

In [4]:
s = (2, 3)
urs = [(s[0] + i, s[1] + i) for i in range(1, min(7-s[0], 7-s[1]) + 1)]

In [19]:
a.board[[np.c_[urs][0]]]

array([['Q', 'P', ' ', ' ', ' ', ' ', 'p', 'q'],
       ['K', 'P', ' ', ' ', ' ', ' ', 'p', 'k']],
      dtype='<U1')

In [9]:
urs

[(3, 4), (4, 5), (5, 6), (6, 7)]

In [15]:
np.c_[urs]

array([[3, 4],
       [4, 5],
       [5, 6],
       [6, 7]])

In [21]:
np.c_[urs].shape

(4, 2)

In [25]:
a.board[np.transpose(np.c_[urs])[0], np.transpose(np.c_[urs])[1]]

array([' ', ' ', 'p', 'n'],
      dtype='<U1')

In [24]:
np.transpose(np.c_[urs])

array([[3, 4, 5, 6],
       [4, 5, 6, 7]])